language: c

install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb
  - sudo dpkg -i /tmp/devkitpro-pacman.deb
# - sudo dkp-pacman -Syu nds-dev
  - sudo dkp-pacman -Syu default-arm7 devkitarm-crtls devkitarm-rules dswifi libfat-nds libfilesystem libnds maxmod-nds devkit-env devkitARM dstools general-tools grit mmutil ndstool
#   Unneeded Packages: nds-examples
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=/opt/devkitpro/devkitARM
  - export DEVKITPPC=/opt/devkitpro/devkitPPC
  - export PATH=$DEVKITPRO/tools/bin:$DEVKITPPC/bin:$PATH

script:
  - make