language: c

install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb
  - sudo dpkg -i /tmp/devkitpro-pacman.deb
  - yes | sudo dkp-pacman -Syu --needed devkitPPC wut-tools
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITPPC=/opt/devkitpro/devkitPPC
  - export PATH=$DEVKITPRO/tools/bin:$DEVKITPPC/bin:$PATH

script:
  - make